project:
  type: book

book:
  title: "Mybook"
  author: "Norah Jones"
  date: "9/20/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - gpa_analysis.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



