project:
  type: book
  output-dir: docs

book:
  title: "Classic and Bayesian Statisitcal Methods: An Introduction With Applications in Python"
  author: "Brandon Scott"
  date: "9/20/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - gpa_analysis.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: lux
  pdf:
    documentclass: scrreprt



