project:
  type: book
  output-dir: docs

book:
  title: "Classic and Bayesian Statistical Methods: An Introduction With Applications in Python"
  author: "Brandon Scott"
  date: "9/20/2023"
  chapters:
    - index.qmd
    - preface.ipynb
    - part: "Chapters"
      chapters:
        - intro_stats.ipynb
        - gpa_analysis.ipynb
        - summary.qmd
        - references.qmd
  navbar:
    right:
      - href: https://thebayesianbandit.com/
        text: Blog
bibliography: references.bib

format:
  html:
    theme: darkly
  pdf:
    documentclass: scrreprt

resources:
  - CNAME

